# @name get_catho_jobs
GET http://localhost:8000/api/catho/list-jobs

###

# @name get_programathor_jobs
GET http://localhost:8000/api/programathor/list-jobs

###

# @name get_jobs_from_all_sources
GET http://localhost:8000/api/jobs/list-all-jobs/
 


